#
# This makefile is part of the Ubiquity Toolkit.
#

PKG_NAME := inetutils
PKG_VERSION := 2.5
PKG := ${PKG_NAME}-${PKG_VERSION}
PKG_SOURCE_URL := https://ftp.gnu.org/gnu/${PKG_NAME}/${PKG}.tar.xz
PKG_HASH :=

# Configuration
CONFIGURE_FLAGS := --disable-ifconfig

# Git
GIT_SOURCE_URL :=
GIT_BRANCH :=

include ${TOPDIR}/rules.mk
