#
# This makefile is part of the Ubiquity Toolkit.
#

PKG_NAME := gmp
PKG_VERSION := 6.3.0
PKG := ${PKG_NAME}-${PKG_VERSION}
PKG_SOURCE_URL := https://ftp.gnu.org/gnu/${PKG_NAME}/${PKG}.tar.xz
PKG_HASH :=

# Configuration
CONFIGURE_FLAGS :=

# Git
GIT_SOURCE_URL :=
GIT_BRANCH :=

include ${TOPDIR}/rules.mk
