#
# This makefile is part of the Ubiquity Toolkit.
#

PKG_NAME := libpcap
PKG_VERSION := 1.10.4
PKG := ${PKG_NAME}-${PKG_VERSION}
PKG_SOURCE_URL := https://www.tcpdump.org/release/${PKG}.tar.xz
PKG_HASH :=

# Configuration
CONFIGURE_FLAGS :=

# Git
GIT_SOURCE_URL :=
GIT_BRANCH :=

include ${TOPDIR}/rules.mk
