#
# This makefile is part of the Ubiquity Toolkit.
#

PKG_NAME := socat
PKG_VERSION := 1.8.0.3
PKG := ${PKG_NAME}-${PKG_VERSION}
PKG_SOURCE_URL := http://www.dest-unreach.org/socat/download/${PKG}.tar.gz
PKG_HASH :=

# Configuration
CONFIGURE_FLAGS := --disable-readline --disable-openssl --bindir=${CURDIR}/${TARGET}/build

# Git
GIT_SOURCE_URL :=
GIT_BRANCH :=

include ${TOPDIR}/rules.mk
